on:
  push:

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - if: ${{ env.GITHUB_TOKEN != null }}
        run: gh api repos/${{ github.repository_owner }}/ghcr-install/dispatches <<< '{"event_type":"run"}' --input -
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
